spring:
  jpa:
    # Spring Boot 3.0.X False
    open-in-view: false
    #Hibernate javax > jakarta
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        default_batch_fetch_size: 100
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.142.31:3306/bside?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: bside
    password: Bside-8-engine
